version: "3.8"

services:
  nodeapp:
    build: .
    container_name: myapp_node
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: myapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: myapp_redis
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: myapp_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@myapp.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_SCRIPT_NAME: "/pgadmin"
    expose:
      - "80"
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  default:
    name: myapp-network
    external: true
